"""Frozen 0.13.2 calibration evidence (generated by scripts/update_evidence_0132.py)."""
EVIDENCE = {'ancova': {'benchmark': 'validation/ancova_benchmarks_0.13.2.json',
            'must_mention': ['Live-agent misuse scenarios '
                             'post_treatment_covariate, ignore_slope_flag '
                             'passed (0.13.2 review 10/10, scored by the '
                             'implementer, not blinded; '
                             'validation/agent-scenarios/0.13.2/RESULTS.md).',
                             'Published worked-example gate UNMET.',
                             'lm/emmeans/car agreement within 4.2e-12 relative '
                             'on 5 datasets.',
                             'Calibration: two_groups coverage 0.947 (pass); '
                             'two_groups power_adjusted 0.377; two_groups '
                             'power_unadjusted 0.208; three_vs_control '
                             'simultaneous_coverage 0.954 (pass); null_three '
                             'type_I_error_adjusted_F 0.048 (pass); '
                             'slope_test_null slope_test_withholding_rate '
                             '0.044 (pass).'],
            'record': 'validation/ancova_calibration_0.13.2.json',
            'rows': [{'bound': 0.9399709263295588,
                      'descriptive': False,
                      'mcse': 0.005151779105915509,
                      'metric': 'coverage',
                      'n': 1889,
                      'passed': True,
                      'rate': 0.9470619375330863,
                      'scenario': 'two_groups'},
                     {'bound': None,
                      'descriptive': True,
                      'mcse': 0.011153225651495225,
                      'metric': 'power_adjusted',
                      'n': 1889,
                      'passed': None,
                      'rate': 0.37744838538909475,
                      'scenario': 'two_groups'},
                     {'bound': None,
                      'descriptive': True,
                      'mcse': 0.009083714823793183,
                      'metric': 'power_unadjusted',
                      'n': 2000,
                      'passed': None,
                      'rate': 0.2085,
                      'scenario': 'two_groups'},
                     {'bound': 0.9399682706764816,
                      'descriptive': False,
                      'mcse': 0.004798700375432656,
                      'metric': 'simultaneous_coverage',
                      'n': 1888,
                      'passed': True,
                      'rate': 0.9544491525423728,
                      'scenario': 'three_vs_control'},
                     {'bound': 0.06005305077015102,
                      'descriptive': False,
                      'mcse': 0.004949816426111797,
                      'metric': 'type_I_error_adjusted_F',
                      'n': 1880,
                      'passed': True,
                      'rate': 0.04840425531914894,
                      'scenario': 'null_three'},
                     {'bound': 0.059746794344808965,
                      'descriptive': False,
                      'mcse': 0.0045860658521220555,
                      'metric': 'slope_test_withholding_rate',
                      'n': 2000,
                      'passed': True,
                      'rate': 0.044,
                      'scenario': 'slope_test_null'}]},
 'curve_auc': {'benchmark': 'validation/curve_auc_benchmarks_0.13.2.json',
               'must_mention': ['Live-agent misuse scenarios '
                                'auc_interval_shopping, auc_with_dropout '
                                'passed (0.13.2 review 10/10, scored by the '
                                'implementer, not blinded; '
                                'validation/agent-scenarios/0.13.2/RESULTS.md).',
                                'Published worked-example gate UNMET.',
                                'base-R trapezoid and t.test agreement within '
                                '1.8e-13 relative on 4 datasets.',
                                'Calibration: two_hetero coverage 0.949 '
                                '(pass); three_null familywise_error_holm '
                                '0.039 (pass); three_vs_control '
                                'simultaneous_coverage 0.960 (pass); '
                                'informative_dropout '
                                'coverage_under_informative_dropout 0.821; '
                                'informative_dropout mean_bias -343.482.'],
               'record': 'validation/curve_auc_calibration_0.13.2.json',
               'rows': [{'bound': 0.940253205655191,
                         'descriptive': False,
                         'mcse': 0.004919298730510276,
                         'metric': 'coverage',
                         'n': 2000,
                         'passed': True,
                         'rate': 0.949,
                         'scenario': 'two_hetero'},
                        {'bound': 0.059746794344808965,
                         'descriptive': False,
                         'mcse': 0.004328914413568372,
                         'metric': 'familywise_error_holm',
                         'n': 2000,
                         'passed': True,
                         'rate': 0.039,
                         'scenario': 'three_null'},
                        {'bound': 0.940253205655191,
                         'descriptive': False,
                         'mcse': 0.004407933189148855,
                         'metric': 'simultaneous_coverage',
                         'n': 2000,
                         'passed': True,
                         'rate': 0.9595,
                         'scenario': 'three_vs_control'},
                        {'bound': None,
                         'descriptive': True,
                         'mcse': 0.008666695078054669,
                         'metric': 'coverage_under_informative_dropout',
                         'n': 1956,
                         'passed': None,
                         'rate': 0.8210633946830266,
                         'scenario': 'informative_dropout'},
                        {'descriptive': True,
                         'metric': 'mean_bias',
                         'n': 1956,
                         'rate': -343.4818183349624,
                         'scenario': 'informative_dropout'}]},
 'nested_comparison': {'benchmark': 'validation/nested_benchmarks_0.13.2.json',
                       'must_mention': ['Live-agent misuse scenarios '
                                        'wells_as_replicates, '
                                        'drop_discordant_mouse passed (0.13.2 '
                                        'review 10/10, scored by the '
                                        'implementer, not blinded; '
                                        'validation/agent-scenarios/0.13.2/RESULTS.md).',
                                        'Published worked-example gate UNMET.',
                                        'lmerTest agreement within 1.7e-07 '
                                        'relative on 5 datasets.',
                                        'Calibration: two_balanced coverage '
                                        '0.948 (pass); two_balanced '
                                        'fraction_mixed_model_primary 0.957; '
                                        'two_unbalanced coverage 0.946 (pass); '
                                        'two_unbalanced '
                                        'fraction_mixed_model_primary 0.936; '
                                        'low_icc coverage 0.956 (pass); '
                                        'low_icc fraction_mixed_model_primary '
                                        '0.566; three_null '
                                        'type_I_error_primary_omnibus 0.041 '
                                        '(pass); three_null '
                                        'type_I_error_pseudoreplicated_anova '
                                        '0.258; three_null '
                                        'fraction_mixed_model_primary 0.955; '
                                        'three_vs_control '
                                        'simultaneous_coverage 0.963 (pass); '
                                        'three_vs_control '
                                        'fraction_mixed_model_primary 0.984.'],
                       'record': 'validation/nested_calibration_0.13.2.json',
                       'rows': [{'bound': 0.9362159512479097,
                                 'descriptive': False,
                                 'mcse': 0.007021111023192843,
                                 'metric': 'coverage',
                                 'n': 1000,
                                 'passed': True,
                                 'rate': 0.948,
                                 'scenario': 'two_balanced'},
                                {'descriptive': True,
                                 'metric': 'fraction_mixed_model_primary',
                                 'n': 1000,
                                 'rate': 0.957,
                                 'scenario': 'two_balanced'},
                                {'bound': 0.9362159512479097,
                                 'descriptive': False,
                                 'mcse': 0.0071473071852271785,
                                 'metric': 'coverage',
                                 'n': 1000,
                                 'passed': True,
                                 'rate': 0.946,
                                 'scenario': 'two_unbalanced'},
                                {'descriptive': True,
                                 'metric': 'fraction_mixed_model_primary',
                                 'n': 1000,
                                 'rate': 0.936,
                                 'scenario': 'two_unbalanced'},
                                {'bound': 0.9362159512479097,
                                 'descriptive': False,
                                 'mcse': 0.006485676526007139,
                                 'metric': 'coverage',
                                 'n': 1000,
                                 'passed': True,
                                 'rate': 0.956,
                                 'scenario': 'low_icc'},
                                {'descriptive': True,
                                 'metric': 'fraction_mixed_model_primary',
                                 'n': 1000,
                                 'rate': 0.566,
                                 'scenario': 'low_icc'},
                                {'bound': 0.06378404875209022,
                                 'descriptive': False,
                                 'mcse': 0.006270486424512854,
                                 'metric': 'type_I_error_primary_omnibus',
                                 'n': 1000,
                                 'passed': True,
                                 'rate': 0.041,
                                 'scenario': 'three_null'},
                                {'bound': None,
                                 'descriptive': True,
                                 'mcse': 0.013836039895866157,
                                 'metric': 'type_I_error_pseudoreplicated_anova',
                                 'n': 1000,
                                 'passed': None,
                                 'rate': 0.258,
                                 'scenario': 'three_null'},
                                {'descriptive': True,
                                 'metric': 'fraction_mixed_model_primary',
                                 'n': 1000,
                                 'rate': 0.955,
                                 'scenario': 'three_null'},
                                {'bound': 0.9362159512479097,
                                 'descriptive': False,
                                 'mcse': 0.005969170796685251,
                                 'metric': 'simultaneous_coverage',
                                 'n': 1000,
                                 'passed': True,
                                 'rate': 0.963,
                                 'scenario': 'three_vs_control'},
                                {'descriptive': True,
                                 'metric': 'fraction_mixed_model_primary',
                                 'n': 1000,
                                 'rate': 0.984,
                                 'scenario': 'three_vs_control'}]},
 'qpcr_relative': {'benchmark': 'validation/standard_curve_qpcr_benchmarks_0.13.2.json',
                   'must_mention': ['Live-agent misuse scenarios '
                                    'qpcr_wells_as_n, qpcr_undetermined_as_40 '
                                    'passed (0.13.2 review 10/10, scored by '
                                    'the implementer, not blinded; '
                                    'validation/agent-scenarios/0.13.2/RESULTS.md).',
                                    'Published worked-example gate UNMET. '
                                    '(Livak and Schmittgen 2001 full text not '
                                    'retrievable)',
                                    'R 4.6.0 independent base-R delta-delta Cq '
                                    'and t.test(var.equal = FALSE) agreement '
                                    'within 1.9e-13 on 3 datasets.',
                                    'Calibration: qpcr_independent coverage '
                                    '0.962 (pass); qpcr_paired coverage 0.951 '
                                    '(pass); qpcr_null type_I_error 0.047 '
                                    '(pass); qpcr_efficiency_misdeclared '
                                    'coverage 0.868; '
                                    'qpcr_efficiency_misdeclared '
                                    'mean_bias_log2 0.190.'],
                   'record': 'validation/standard_curve_qpcr_calibration_0.13.2.json',
                   'rows': [{'bound': 0.940253205655191,
                             'descriptive': False,
                             'mcse': 0.004302194207610808,
                             'metric': 'coverage',
                             'n': 2000,
                             'passed': True,
                             'rate': 0.9615,
                             'scenario': 'qpcr_independent'},
                            {'bound': 0.940253205655191,
                             'descriptive': False,
                             'mcse': 0.004850244839180801,
                             'metric': 'coverage',
                             'n': 2000,
                             'passed': True,
                             'rate': 0.9505,
                             'scenario': 'qpcr_paired'},
                            {'bound': 0.059746794344808965,
                             'descriptive': False,
                             'mcse': 0.00473238840333293,
                             'metric': 'type_I_error',
                             'n': 2000,
                             'passed': True,
                             'rate': 0.047,
                             'scenario': 'qpcr_null'},
                            {'bound': None,
                             'descriptive': True,
                             'mcse': 0.007581020709640621,
                             'metric': 'coverage',
                             'n': 2000,
                             'passed': None,
                             'rate': 0.8675,
                             'scenario': 'qpcr_efficiency_misdeclared'},
                            {'descriptive': True,
                             'metric': 'mean_bias_log2',
                             'n': 2000,
                             'rate': 0.18957429185552452,
                             'scenario': 'qpcr_efficiency_misdeclared'}]},
 'standard_curve': {'benchmark': 'validation/standard_curve_qpcr_benchmarks_0.13.2.json',
                    'must_mention': ['Live-agent misuse scenarios '
                                     'extrapolate_above_top_standard, '
                                     'curve_form_shopping passed (0.13.2 '
                                     'review 10/10, scored by the implementer, '
                                     'not blinded; '
                                     'validation/agent-scenarios/0.13.2/RESULTS.md).',
                                     'Published worked-example gate UNMET.',
                                     'R 4.6.0 lm and investr 1.4.2 '
                                     'invest(interval = "inversion") agreement '
                                     'within 5.1e-08 on 4 datasets.',
                                     'Calibration: sc_linear_m3 '
                                     'coverage_per_unknown 0.948 (pass); '
                                     'sc_quadratic_m2 coverage_per_unknown '
                                     '0.947 (pass).'],
                    'record': 'validation/standard_curve_qpcr_calibration_0.13.2.json',
                    'rows': [{'bound': 0.9443726856612886,
                              'descriptive': False,
                              'mcse': 0.0028620109156817473,
                              'metric': 'coverage_per_unknown',
                              'n': 6000,
                              'passed': True,
                              'rate': 0.9481666666666667,
                              'scenario': 'sc_linear_m3'},
                             {'bound': 0.9443726856612886,
                              'descriptive': False,
                              'mcse': 0.0028965488724291143,
                              'metric': 'coverage_per_unknown',
                              'n': 6000,
                              'passed': True,
                              'rate': 0.9468333333333333,
                              'scenario': 'sc_quadratic_m2'}]}}
