"""Observed 0.11.1 evidence. Generated without changing scientific results."""
EVIDENCE = {'contingency': {'calibration_rows': [{'bound': 0.9362159512479097,
                                       'count': 902,
                                       'mcse': 0.009401914698613255,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': False,
                                       'population': 'all_evaluable',
                                       'rate': 0.902,
                                       'scenario': 'wilson_n20_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 902,
                                       'mcse': 0.009401914698613255,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': False,
                                       'population': 'reportable_only',
                                       'rate': 0.902,
                                       'scenario': 'wilson_n20_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 944,
                                       'mcse': 0.007270763371201131,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.944,
                                       'scenario': 'wilson_n20_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 944,
                                       'mcse': 0.007270763371201131,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.944,
                                       'scenario': 'wilson_n20_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 958,
                                       'mcse': 0.006343185319695463,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.958,
                                       'scenario': 'wilson_n100_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 958,
                                       'mcse': 0.006343185319695463,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.958,
                                       'scenario': 'wilson_n100_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 934,
                                       'mcse': 0.007851369307324675,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': False,
                                       'population': 'all_evaluable',
                                       'rate': 0.934,
                                       'scenario': 'wilson_n100_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 934,
                                       'mcse': 0.007851369307324675,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': False,
                                       'population': 'reportable_only',
                                       'rate': 0.934,
                                       'scenario': 'wilson_n100_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 988,
                                       'mcse': 0.003443254274665176,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.988,
                                       'scenario': 'clopper_pearson_n20_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 988,
                                       'mcse': 0.003443254274665176,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.988,
                                       'scenario': 'clopper_pearson_n20_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 960,
                                       'mcse': 0.00619677335393187,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.96,
                                       'scenario': 'clopper_pearson_n20_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 960,
                                       'mcse': 0.00619677335393187,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.96,
                                       'scenario': 'clopper_pearson_n20_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 991,
                                       'mcse': 0.0029864694875387575,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.991,
                                       'scenario': 'clopper_pearson_n100_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 991,
                                       'mcse': 0.0029864694875387575,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.991,
                                       'scenario': 'clopper_pearson_n100_p0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 964,
                                       'mcse': 0.005891010100144119,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.964,
                                       'scenario': 'clopper_pearson_n100_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 964,
                                       'mcse': 0.005891010100144119,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.964,
                                       'scenario': 'clopper_pearson_n100_p0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 998,
                                       'mcse': 0.0014127986409959495,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.998,
                                       'scenario': 'newcombe_n20_0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 998,
                                       'mcse': 0.0014127986409959495,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.998,
                                       'scenario': 'newcombe_n20_0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 948,
                                       'mcse': 0.007021111023192843,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.948,
                                       'scenario': 'newcombe_n20_0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 948,
                                       'mcse': 0.007021111023192843,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.948,
                                       'scenario': 'newcombe_n20_0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 962,
                                       'mcse': 0.006046155803483734,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.962,
                                       'scenario': 'newcombe_n100_0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 962,
                                       'mcse': 0.006046155803483734,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.962,
                                       'scenario': 'newcombe_n100_0.05',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 938,
                                       'mcse': 0.00762600813007697,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.938,
                                       'scenario': 'newcombe_n100_0.5',
                                       'stress': False},
                                      {'bound': 0.9362159512479097,
                                       'count': 938,
                                       'mcse': 0.00762600813007697,
                                       'metric': 'coverage',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.938,
                                       'scenario': 'newcombe_n100_0.5',
                                       'stress': False},
                                      {'bound': 0.06378404875209022,
                                       'count': 2,
                                       'mcse': 0.0014127986409959489,
                                       'metric': 'null_size',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.002,
                                       'scenario': 'fisher_n10',
                                       'stress': False},
                                      {'bound': 0.06378404875209022,
                                       'count': 2,
                                       'mcse': 0.0014127986409959489,
                                       'metric': 'null_size',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.002,
                                       'scenario': 'fisher_n10',
                                       'stress': False},
                                      {'bound': 0.06378404875209022,
                                       'count': 22,
                                       'mcse': 0.0046385342512479085,
                                       'metric': 'null_size',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'all_evaluable',
                                       'rate': 0.022,
                                       'scenario': 'fisher_n50',
                                       'stress': False},
                                      {'bound': 0.06378404875209022,
                                       'count': 22,
                                       'mcse': 0.0046385342512479085,
                                       'metric': 'null_size',
                                       'n': 1000,
                                       'passed': True,
                                       'population': 'reportable_only',
                                       'rate': 0.022,
                                       'scenario': 'fisher_n50',
                                       'stress': False}],
                 'must_mention': ['Calibration miss: wilson_n20_p0.05 coverage '
                                  '(all_evaluable), 902/1000; stress=False.',
                                  'Calibration miss: wilson_n20_p0.05 coverage '
                                  '(reportable_only), 902/1000; stress=False.',
                                  'Calibration miss: wilson_n100_p0.5 coverage '
                                  '(all_evaluable), 934/1000; stress=False.',
                                  'Calibration miss: wilson_n100_p0.5 coverage '
                                  '(reportable_only), 934/1000; stress=False.'],
                 'record': 'validation/routine_calibration_0.11.1.json'},
 'correlation_regression': {'calibration_rows': [],
                            'must_mention': ['Correlation/regression interval '
                                             'calibration not separately '
                                             'simulated; numerical R '
                                             'comparisons only.'],
                            'record': 'validation/routine_calibration_0.11.1.json'},
 'factorial_anova': {'calibration_rows': [{'bound': 0.06378404875209022,
                                           'count': 49,
                                           'mcse': 0.006826346021115542,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'all_evaluable',
                                           'rate': 0.049,
                                           'scenario': 'anova_2_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 49,
                                           'mcse': 0.006826346021115542,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'reportable_only',
                                           'rate': 0.049,
                                           'scenario': 'anova_2_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 62,
                                           'mcse': 0.007626008130076967,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'all_evaluable',
                                           'rate': 0.062,
                                           'scenario': 'anova_2_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 62,
                                           'mcse': 0.007626008130076967,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'reportable_only',
                                           'rate': 0.062,
                                           'scenario': 'anova_2_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 44,
                                           'mcse': 0.006485676526007136,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'all_evaluable',
                                           'rate': 0.044,
                                           'scenario': 'anova_2_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 44,
                                           'mcse': 0.006485676526007136,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'reportable_only',
                                           'rate': 0.044,
                                           'scenario': 'anova_2_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 216,
                                           'mcse': 0.013013224043256921,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'all_evaluable',
                                           'rate': 0.216,
                                           'scenario': 'anova_2_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 216,
                                           'mcse': 0.013013224043256921,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'reportable_only',
                                           'rate': 0.216,
                                           'scenario': 'anova_2_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 284,
                                           'mcse': 0.014259873772232347,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'all_evaluable',
                                           'rate': 0.284,
                                           'scenario': 'anova_2_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 284,
                                           'mcse': 0.014259873772232347,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'reportable_only',
                                           'rate': 0.284,
                                           'scenario': 'anova_2_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 188,
                                           'mcse': 0.012355403676124872,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'all_evaluable',
                                           'rate': 0.188,
                                           'scenario': 'anova_2_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 188,
                                           'mcse': 0.012355403676124872,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'reportable_only',
                                           'rate': 0.188,
                                           'scenario': 'anova_2_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 49,
                                           'mcse': 0.006826346021115542,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'all_evaluable',
                                           'rate': 0.049,
                                           'scenario': 'anova_3_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 49,
                                           'mcse': 0.006826346021115542,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'reportable_only',
                                           'rate': 0.049,
                                           'scenario': 'anova_3_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 73,
                                           'mcse': 0.008226238508577295,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'all_evaluable',
                                           'rate': 0.073,
                                           'scenario': 'anova_3_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 73,
                                           'mcse': 0.008226238508577295,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'reportable_only',
                                           'rate': 0.073,
                                           'scenario': 'anova_3_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 44,
                                           'mcse': 0.006485676526007136,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'all_evaluable',
                                           'rate': 0.044,
                                           'scenario': 'anova_3_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 44,
                                           'mcse': 0.006485676526007136,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': True,
                                           'population': 'reportable_only',
                                           'rate': 0.044,
                                           'scenario': 'anova_3_equal',
                                           'stress': False},
                                          {'bound': 0.06378404875209022,
                                           'count': 219,
                                           'mcse': 0.013078187947877183,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'all_evaluable',
                                           'rate': 0.219,
                                           'scenario': 'anova_3_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 219,
                                           'mcse': 0.013078187947877183,
                                           'metric': 'C(a, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'reportable_only',
                                           'rate': 0.219,
                                           'scenario': 'anova_3_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 265,
                                           'mcse': 0.013956181426163821,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'all_evaluable',
                                           'rate': 0.265,
                                           'scenario': 'anova_3_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 265,
                                           'mcse': 0.013956181426163821,
                                           'metric': 'C(a, Sum):C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'reportable_only',
                                           'rate': 0.265,
                                           'scenario': 'anova_3_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 259,
                                           'mcse': 0.013853483316480371,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'all_evaluable',
                                           'rate': 0.259,
                                           'scenario': 'anova_3_heteroscedastic',
                                           'stress': True},
                                          {'bound': 0.06378404875209022,
                                           'count': 259,
                                           'mcse': 0.013853483316480371,
                                           'metric': 'C(b, Sum)',
                                           'n': 1000,
                                           'passed': False,
                                           'population': 'reportable_only',
                                           'rate': 0.259,
                                           'scenario': 'anova_3_heteroscedastic',
                                           'stress': True}],
                     'must_mention': ['Calibration miss: '
                                      'anova_2_heteroscedastic C(a, Sum) '
                                      '(all_evaluable), 216/1000; stress=True.',
                                      'Calibration miss: '
                                      'anova_2_heteroscedastic C(a, Sum) '
                                      '(reportable_only), 216/1000; '
                                      'stress=True.',
                                      'Calibration miss: '
                                      'anova_2_heteroscedastic C(a, Sum):C(b, '
                                      'Sum) (all_evaluable), 284/1000; '
                                      'stress=True.',
                                      'Calibration miss: '
                                      'anova_2_heteroscedastic C(a, Sum):C(b, '
                                      'Sum) (reportable_only), 284/1000; '
                                      'stress=True.',
                                      'Calibration miss: '
                                      'anova_2_heteroscedastic C(b, Sum) '
                                      '(all_evaluable), 188/1000; stress=True.',
                                      'Calibration miss: '
                                      'anova_2_heteroscedastic C(b, Sum) '
                                      '(reportable_only), 188/1000; '
                                      'stress=True.',
                                      'Calibration miss: anova_3_equal C(a, '
                                      'Sum):C(b, Sum) (all_evaluable), '
                                      '73/1000; stress=False.',
                                      'Calibration miss: anova_3_equal C(a, '
                                      'Sum):C(b, Sum) (reportable_only), '
                                      '73/1000; stress=False.',
                                      'Calibration miss: '
                                      'anova_3_heteroscedastic C(a, Sum) '
                                      '(all_evaluable), 219/1000; stress=True.',
                                      'Calibration miss: '
                                      'anova_3_heteroscedastic C(a, Sum) '
                                      '(reportable_only), 219/1000; '
                                      'stress=True.',
                                      'Calibration miss: '
                                      'anova_3_heteroscedastic C(a, Sum):C(b, '
                                      'Sum) (all_evaluable), 265/1000; '
                                      'stress=True.',
                                      'Calibration miss: '
                                      'anova_3_heteroscedastic C(a, Sum):C(b, '
                                      'Sum) (reportable_only), 265/1000; '
                                      'stress=True.',
                                      'Calibration miss: '
                                      'anova_3_heteroscedastic C(b, Sum) '
                                      '(all_evaluable), 259/1000; stress=True.',
                                      'Calibration miss: '
                                      'anova_3_heteroscedastic C(b, Sum) '
                                      '(reportable_only), 259/1000; '
                                      'stress=True.'],
                     'record': 'validation/routine_calibration_0.11.1.json'},
 'method_comparison': {'calibration_rows': [{'bound': 0.9362159512479097,
                                             'count': 950,
                                             'mcse': 0.006892024376045114,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.95,
                                             'scenario': 'deming_n30_ratio0.25',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 950,
                                             'mcse': 0.006892024376045114,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.95,
                                             'scenario': 'deming_n30_ratio0.25',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 956,
                                             'mcse': 0.006485676526007139,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.956,
                                             'scenario': 'deming_n30_ratio1',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 956,
                                             'mcse': 0.006485676526007139,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.956,
                                             'scenario': 'deming_n30_ratio1',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.951,
                                             'scenario': 'deming_n30_ratio4',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.951,
                                             'scenario': 'deming_n30_ratio4',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.951,
                                             'scenario': 'deming_n100_ratio0.25',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.951,
                                             'scenario': 'deming_n100_ratio0.25',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 949,
                                             'mcse': 0.006956938982052382,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.949,
                                             'scenario': 'deming_n100_ratio1',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 949,
                                             'mcse': 0.006956938982052382,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.949,
                                             'scenario': 'deming_n100_ratio1',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.951,
                                             'scenario': 'deming_n100_ratio4',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.951,
                                             'scenario': 'deming_n100_ratio4',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.951,
                                             'scenario': 'passing_bablok_n30_tiesFalse',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 951,
                                             'mcse': 0.006826346021115546,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.951,
                                             'scenario': 'passing_bablok_n30_tiesFalse',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 1000,
                                             'mcse': 0.0,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 1.0,
                                             'scenario': 'passing_bablok_n30_tiesTrue',
                                             'stress': True},
                                            {'bound': 0.9361604820147335,
                                             'count': 992,
                                             'mcse': 0.0,
                                             'metric': 'slope_coverage',
                                             'n': 992,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 1.0,
                                             'scenario': 'passing_bablok_n30_tiesTrue',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 962,
                                             'mcse': 0.006046155803483734,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.962,
                                             'scenario': 'passing_bablok_n100_tiesFalse',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 962,
                                             'mcse': 0.006046155803483734,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.962,
                                             'scenario': 'passing_bablok_n100_tiesFalse',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 1000,
                                             'mcse': 0.0,
                                             'metric': 'slope_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 1.0,
                                             'scenario': 'passing_bablok_n100_tiesTrue',
                                             'stress': True},
                                            {'bound': 0.9359536444640554,
                                             'count': 963,
                                             'mcse': 0.0,
                                             'metric': 'slope_coverage',
                                             'n': 963,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 1.0,
                                             'scenario': 'passing_bablok_n100_tiesTrue',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 954,
                                             'mcse': 0.006624499981130654,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.954,
                                             'scenario': 'loa_n30_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 954,
                                             'mcse': 0.006624499981130654,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.954,
                                             'scenario': 'loa_n30_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 957,
                                             'mcse': 0.006414904519944161,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.957,
                                             'scenario': 'loa_n30_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 957,
                                             'mcse': 0.006414904519944161,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.957,
                                             'scenario': 'loa_n30_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 15,
                                             'mcse': 0.003843826218756514,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'all_evaluable',
                                             'rate': 0.015,
                                             'scenario': 'loa_n30_skew',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 15,
                                             'mcse': 0.003843826218756514,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'reportable_only',
                                             'rate': 0.015,
                                             'scenario': 'loa_n30_skew',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 430,
                                             'mcse': 0.015655669899432602,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'all_evaluable',
                                             'rate': 0.43,
                                             'scenario': 'loa_n30_skew',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 430,
                                             'mcse': 0.015655669899432602,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'reportable_only',
                                             'rate': 0.43,
                                             'scenario': 'loa_n30_skew',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 952,
                                             'mcse': 0.006759881655768837,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.952,
                                             'scenario': 'loa_n100_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 952,
                                             'mcse': 0.006759881655768837,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.952,
                                             'scenario': 'loa_n100_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 955,
                                             'mcse': 0.00655553201502365,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'all_evaluable',
                                             'rate': 0.955,
                                             'scenario': 'loa_n100_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 955,
                                             'mcse': 0.00655553201502365,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': True,
                                             'population': 'reportable_only',
                                             'rate': 0.955,
                                             'scenario': 'loa_n100_normal',
                                             'stress': False},
                                            {'bound': 0.9362159512479097,
                                             'count': 0,
                                             'mcse': 0.0,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'all_evaluable',
                                             'rate': 0.0,
                                             'scenario': 'loa_n100_skew',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 0,
                                             'mcse': 0.0,
                                             'metric': 'limit_0_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'reportable_only',
                                             'rate': 0.0,
                                             'scenario': 'loa_n100_skew',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 178,
                                             'mcse': 0.012096115078817662,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'all_evaluable',
                                             'rate': 0.178,
                                             'scenario': 'loa_n100_skew',
                                             'stress': True},
                                            {'bound': 0.9362159512479097,
                                             'count': 178,
                                             'mcse': 0.012096115078817662,
                                             'metric': 'limit_1_coverage',
                                             'n': 1000,
                                             'passed': False,
                                             'population': 'reportable_only',
                                             'rate': 0.178,
                                             'scenario': 'loa_n100_skew',
                                             'stress': True}],
                       'must_mention': ['Calibration miss: loa_n30_skew '
                                        'limit_0_coverage (all_evaluable), '
                                        '15/1000; stress=True.',
                                        'Calibration miss: loa_n30_skew '
                                        'limit_0_coverage (reportable_only), '
                                        '15/1000; stress=True.',
                                        'Calibration miss: loa_n30_skew '
                                        'limit_1_coverage (all_evaluable), '
                                        '430/1000; stress=True.',
                                        'Calibration miss: loa_n30_skew '
                                        'limit_1_coverage (reportable_only), '
                                        '430/1000; stress=True.',
                                        'Calibration miss: loa_n100_skew '
                                        'limit_0_coverage (all_evaluable), '
                                        '0/1000; stress=True.',
                                        'Calibration miss: loa_n100_skew '
                                        'limit_0_coverage (reportable_only), '
                                        '0/1000; stress=True.',
                                        'Calibration miss: loa_n100_skew '
                                        'limit_1_coverage (all_evaluable), '
                                        '178/1000; stress=True.',
                                        'Calibration miss: loa_n100_skew '
                                        'limit_1_coverage (reportable_only), '
                                        '178/1000; stress=True.'],
                       'record': 'validation/routine_calibration_0.11.1.json'}}
